version: '2.2'
volumes:
  upload_files: {}

services:
  uploadfileboot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - upload_files:/files
    container_name: uploadfileboot
    restart: always